version: '3.9'

services:
  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://localhost:3000}
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:3000}
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  backend-data: {}
